services:
  postgres:
    image: postgres:16-alpine
    networks:
      - trava-network

  trava-api:
    build:
      context: .
      dockerfile: backend/src/Trava.API/Dockerfile
    image: ghcr.io/ndmthuan97/trava-api:latest
    networks:
      - trava-network

volumes:
  postgres_data:


networks:
  trava-network:
    driver: bridge
