services:
  trava-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:9001
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__ValidIssuer=${JWT_VALID_ISSUER}
      - JwtSettings__ValidAudience=${JWT_VALID_AUDIENCE}
      - JwtSettings__ExpiryInSecond=${JWT_EXPIRY_IN_SECONDS}
