name: Build & Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.x.x"
  SOLUTION_PATH: "./backend/backend.sln"
  API_PROJECT_PATH: "backend/src/Trava.API"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }} --verbosity minimal

      - name: Build & Publish
        run: |
          dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --verbosity minimal
          dotnet publish ${{ env.API_PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }} --verbosity minimal

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: trava-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
